// The "Hot rules from strata" block in CLAUDE.md and AGENTS.md (ADR-0019).
// Subagents and Codex read the adapters but never open .strata/memory/, so the
// hot learnings are mirrored there. Only text between the markers is touched.

import path from 'node:path'
import { readLf, writeText, exists } from './core.mjs'
import { readLearnings, hotSubset, byTrigger, firstSentence } from './model.mjs'

export const BEGIN = '<!-- strata:hot-rules:begin -->'
export const END = '<!-- strata:hot-rules:end -->'
export const ADAPTERS = ['CLAUDE.md', 'AGENTS.md']
export const BUDGET = { rules: 25, chars: 4000 }

function capitalize(s) { return s ? s[0].toUpperCase() + s.slice(1) : s }

// The inner text of the block (between the marker lines), LF, no trailing newline.
export function renderHotRules(project) {
  const hot = hotSubset(readLearnings(project)).sort(byTrigger)
  const lines = [
    '## Hot rules from strata',
    '',
    'Generated by strata from the `hot: true` learnings in `.strata/memory/learnings/`. Edit those files, not this block; `/strata:save` refreshes it.',
    '',
  ]
  let used = 0
  let shown = 0
  for (const l of hot) {
    const trigger = capitalize(String(l.trigger || l.slug).replace(/\s+/g, ' ').trim())
    const lesson = firstSentence(l.lesson)
    const line = `- **${trigger}:** ${lesson} ([rule](.strata/memory/learnings/${l.name}))`
    if (shown >= BUDGET.rules || used + line.length > BUDGET.chars) break
    lines.push(line)
    used += line.length
    shown++
  }
  const more = hot.length - shown
  if (!hot.length) lines.push('- _No hot rules yet. Mark a learning `hot: true` to list it here._')
  if (more > 0) lines.push(`- ${more} more hot rule${more === 1 ? '' : 's'}: see [.strata/memory/MEMORY.md](.strata/memory/MEMORY.md).`)
  return { text: lines.join('\n'), total: hot.length, shown, overflow: more }
}

export function blockText(inner) { return `${BEGIN}\n${inner}\n${END}` }

// Locate the marker pair. Returns null when either marker is missing or out of order.
function findBlock(text) {
  const b = text.indexOf(BEGIN)
  if (b < 0) return null
  const e = text.indexOf(END, b + BEGIN.length)
  if (e < 0) return null
  return { start: b, end: e + END.length }
}

// Refresh the block in every adapter that has the markers. With `check`, only
// report which ones differ. With `install`, append the block to adapters that
// exist but lack it.
export function syncHotRules(project, { check = false, install = false } = {}) {
  const rendered = renderHotRules(project)
  const block = blockText(rendered.text)
  const results = []
  for (const name of ADAPTERS) {
    const file = path.join(project, name)
    if (!exists(file)) continue
    const text = readLf(file)
    const at = findBlock(text)
    if (!at) {
      if (install && !check) {
        const sep = text.endsWith('\n\n') ? '' : text.endsWith('\n') ? '\n' : '\n\n'
        writeText(file, text + sep + block + '\n')
        results.push({ file: name, state: 'installed' })
      } else {
        results.push({ file: name, state: 'no-markers' })
      }
      continue
    }
    const next = text.slice(0, at.start) + block + text.slice(at.end)
    if (next === text) { results.push({ file: name, state: 'current' }); continue }
    if (check) { results.push({ file: name, state: 'stale' }); continue }
    writeText(file, next)
    results.push({ file: name, state: 'updated' })
  }
  return { ...rendered, results }
}
