// Generated views: issues/ACTIVE.md, OPEN.md, PARKED.md, memory/learnings/INDEX.md
// and the rules table in memory/MEMORY.md. Each is rendered from item frontmatter
// in a fixed order, so a re-run with no new work changes nothing (ADR-0004).
//
// Everything up to and including a view's `<!-- GENERATED … -->` line is the
// header and is kept as written; everything after it is generated. In MEMORY.md
// only the rules table after that line is generated.

import path from 'node:path'
import { readLf, writeText, exists, relPosix } from './core.mjs'
import { parseFrontmatter } from './frontmatter.mjs'
import {
  readIssues, readLearnings, hotSubset, byTrigger, byIssueOrder, byId, cell,
} from './model.mjs'
import { syncHotRules } from './adapters.mjs'

export const MARKER_RE = /^<!--\s*GENERATED\b.*-->[ \t]*$/m
const DEFAULT_MARKER = '<!-- GENERATED by strata from item frontmatter; do not hand-edit, edit the item files instead -->'

export const VIEW_PATHS = {
  active: '.strata/issues/ACTIVE.md',
  open: '.strata/issues/OPEN.md',
  parked: '.strata/issues/PARKED.md',
  index: '.strata/memory/learnings/INDEX.md',
  memory: '.strata/memory/MEMORY.md',
}

const DEFAULT_HEADERS = {
  active: ['# Active issues', '', 'Everything `status: in-progress`. Loaded at `/strata:load`.'],
  open: ['# Open backlog', '', 'Everything `status: open`, grouped by area, severity first. Consulted on demand when picking work, not auto-loaded.'],
  parked: ['# Parked', '', 'Everything `status: parked`, with revive triggers. `/strata:save` checks these triggers against the session and revives matches.'],
  index: ['# Learnings index', '', 'Operation-keyed behavioral rules: one lesson per file, fired by trigger, origin `success | failure`. To add one, copy `_TEMPLATE.md` to `<slug>.md`.'],
}

export const TABLE_HEADERS = {
  active: ['| Id | Type | Sev | Area | What |', '|---|---|---|---|---|'],
  open: ['| Id | Type | Sev | What |', '|---|---|---|---|'],
  parked: ['| Id | What | Revive when |', '|---|---|---|'],
  index: ['| Trigger | Applies when | Origin | File |', '|---|---|---|---|'],
  memory: ['| When you are about to… | Read |', '|---|---|'],
}

const NO_AREA = '(no area)'

// --- row model ----------------------------------------------------------------
// A row is { key, line, sort: [...], group? }. The renderer and the merge driver
// both sort rows with sortRows, so a merged view lands in the same order a fresh
// render would use.

function issueLink(i) { return `[${cell(i.id || path.basename(i.rel, '.md'))}](${i.rel})` }

export function issueRows(kind, issues) {
  const status = { active: 'in-progress', open: 'open', parked: 'parked' }[kind]
  const sel = issues.filter((i) => !i.archived && i.status === status && i.frontmatter)
  sel.sort(kind === 'parked' ? byId : byIssueOrder)
  return sel.map((i) => {
    let line
    if (kind === 'active') line = `| ${issueLink(i)} | ${cell(i.type)} | ${cell(i.severity)} | ${cell(i.area)} | ${cell(i.what, 140)} |`
    else if (kind === 'open') line = `| ${issueLink(i)} | ${cell(i.type)} | ${cell(i.severity)} | ${cell(i.what, 140)} |`
    else line = `| ${issueLink(i)} | ${cell(i.what, 140)} | ${cell(i.revive, 160)} |`
    return { key: i.id || i.rel, line, group: kind === 'open' ? (String(i.area || '').replace(/\s+/g, ' ').trim() || NO_AREA) : undefined }
  })
}

export function learningRows(kind, learnings) {
  const list = (kind === 'memory' ? hotSubset(learnings) : learnings.slice()).sort(byTrigger)
  return list.map((l) => ({
    key: l.name,
    line: kind === 'memory'
      ? `| ${cell(l.trigger || l.slug)} | [${cell(l.slug)}](learnings/${l.name}) |`
      : `| ${cell(l.trigger)} | ${cell(l.appliesWhen) || '—'} | ${cell(l.origin)} | [${cell(l.name)}](${l.name}) |`,
  }))
}

// Sort key read back from a rendered line, so merged rows sort like fresh ones.
const SEV = { high: 0, med: 1, low: 2 }
function cellsOf(line) {
  return line.replace(/^\|/, '').replace(/\|\s*$/, '').split(/(?<!\\)\|/).map((c) => c.trim())
}
function linkText(c) { const m = /^\[([^\]]*)\]/.exec(c); return m ? m[1] : c }
function linkTarget(c) { const m = /\]\(([^)]*)\)/.exec(c); return m ? m[1] : c }

export function rowSortKey(kind, line) {
  const c = cellsOf(line)
  if (kind === 'active' || kind === 'open') {
    const sev = Object.prototype.hasOwnProperty.call(SEV, c[2]) ? SEV[c[2]] : 3
    return [sev, linkText(c[0]), linkTarget(c[0])]
  }
  if (kind === 'parked') return [linkText(c[0]), linkTarget(c[0])]
  if (kind === 'index') return [c[0].toLowerCase(), linkTarget(c[3] || '')]
  return [c[0].toLowerCase(), linkTarget(c[1] || '')] // memory
}

export function rowKey(kind, line) {
  const c = cellsOf(line)
  if (kind === 'index') return linkTarget(c[3] || '')
  if (kind === 'memory') return path.posix.basename(linkTarget(c[1] || ''))
  return linkText(c[0])
}

function cmp(a, b) {
  for (let i = 0; i < Math.max(a.length, b.length); i++) {
    if (a[i] === b[i]) continue
    if (a[i] === undefined) return -1
    if (b[i] === undefined) return 1
    return a[i] < b[i] ? -1 : 1
  }
  return 0
}

export function sortRows(kind, rows) {
  return rows.slice().sort((x, y) => cmp(rowSortKey(kind, x.line), rowSortKey(kind, y.line)))
}

function groupOrder(a, b) {
  if (a === b) return 0
  if (a === NO_AREA) return 1
  if (b === NO_AREA) return -1
  const x = a.toLowerCase(); const y = b.toLowerCase()
  return x < y ? -1 : x > y ? 1 : (a < b ? -1 : 1)
}

// --- region text ----------------------------------------------------------------
// The generated region of an issue view or INDEX, starting right after the marker line.
export function renderRegion(kind, rows, { anyLearnings = false } = {}) {
  const out = ['']
  if (kind === 'open') {
    if (!rows.length) return '\n_No open issues._\n'
    const groups = new Map()
    for (const r of rows) {
      if (!groups.has(r.group)) groups.set(r.group, [])
      groups.get(r.group).push(r)
    }
    for (const g of [...groups.keys()].sort(groupOrder)) {
      out.push(`### ${g}`, '', ...TABLE_HEADERS.open, ...sortRows('open', groups.get(g)).map((r) => r.line), '')
    }
    return out.join('\n')
  }
  out.push(...TABLE_HEADERS[kind])
  const sorted = sortRows(kind, rows)
  out.push(...sorted.map((r) => r.line))
  if (!rows.length) {
    if (kind === 'active') out.push('', '_Nothing in progress. Pick from [OPEN.md](OPEN.md)._')
    else if (kind === 'parked') out.push('', '_Nothing parked._')
    else if (kind === 'index') out.push('| _no learnings yet_ | — | — | — |')
  }
  void anyLearnings
  return out.join('\n') + '\n'
}

export function renderMemoryTable(rows, header, { anyLearnings }) {
  const h = header && header.length === 2 ? header : TABLE_HEADERS.memory
  const lines = [...h]
  if (rows.length) lines.push(...sortRows('memory', rows).map((r) => r.line))
  else if (anyLearnings) lines.push('| _no hot rules yet; full list in [learnings/INDEX.md](learnings/INDEX.md)_ | — |')
  else lines.push('| _no learnings yet_ | — |')
  return lines
}

// Split a view into header (through the marker line) and region.
export function splitView(text) {
  const m = MARKER_RE.exec(text)
  if (!m) return null
  const end = m.index + m[0].length
  const nl = text.indexOf('\n', end)
  const cut = nl < 0 ? text.length : nl + 1
  return { header: text.slice(0, cut), region: text.slice(cut) }
}

// MEMORY.md: locate the generated rules table (line indexes, end exclusive).
export function findMemoryTable(lines) {
  let from = lines.findIndex((l) => MARKER_RE.test(l))
  if (from < 0) from = lines.findIndex((l) => /^##\s+Rules by trigger/i.test(l))
  if (from < 0) return null
  let start = -1
  for (let i = from + 1; i < lines.length; i++) {
    if (/^\|/.test(lines[i])) { start = i; break }
    if (/^##\s/.test(lines[i])) break
  }
  if (start < 0) return null
  let end = start
  while (end < lines.length && /^\|/.test(lines[end])) end++
  return { start, end }
}

function freshHeader(kind, existing) {
  const lines = DEFAULT_HEADERS[kind].slice()
  const h1 = existing && /^#\s.+$/m.exec(existing)
  if (h1) lines[0] = h1[0]
  return lines.join('\n') + '\n\n' + DEFAULT_MARKER + '\n'
}

// --- whole-project render ---------------------------------------------------------
export function viewsExternal(project) {
  const text = readLf(path.join(project, '.strata', 'MANIFEST.md'))
  if (!text) return false
  return String(parseFrontmatter(text).data.generated_views || '').toLowerCase() === 'external'
}

// Compute every view's next content. Returns [{ kind, file, rel, state, next }].
export function planViews(project) {
  const issues = readIssues(project)
  const learnings = readLearnings(project)
  const plans = []
  for (const kind of ['active', 'open', 'parked', 'index']) {
    const rel = VIEW_PATHS[kind]
    const file = path.join(project, rel)
    const cur = readLf(file)
    const rows = kind === 'index' ? learningRows('index', learnings) : issueRows(kind, issues)
    const split = cur != null ? splitView(cur) : null
    const header = split ? split.header : freshHeader(kind, cur)
    const next = header + renderRegion(kind, rows)
    plans.push({ kind, file, rel, cur, next, state: cur == null ? 'created' : cur === next ? 'current' : 'updated' })
  }
  {
    const rel = VIEW_PATHS.memory
    const file = path.join(project, rel)
    const cur = readLf(file)
    if (cur == null) {
      plans.push({ kind: 'memory', file, rel, cur, next: null, state: 'missing' })
    } else {
      const lines = cur.split('\n')
      const at = findMemoryTable(lines)
      if (!at) {
        plans.push({ kind: 'memory', file, rel, cur, next: null, state: 'no-table' })
      } else {
        const existing = lines.slice(at.start, at.end)
        const header = existing.length >= 2 && /^\|[\s:-]+\|/.test(existing[1]) ? existing.slice(0, 2) : null
        const table = renderMemoryTable(learningRows('memory', learnings), header, { anyLearnings: learnings.length > 0 })
        const next = [...lines.slice(0, at.start), ...table, ...lines.slice(at.end)].join('\n')
        plans.push({ kind: 'memory', file, rel, cur, next, state: cur === next ? 'current' : 'updated' })
      }
    }
  }
  return plans
}

// Regenerate (or, with check, only compare) every view and the hot-rules blocks.
export function syncViews(project, { check = false } = {}) {
  const external = viewsExternal(project)
  const views = []
  if (!external) {
    for (const p of planViews(project)) {
      let state = p.state
      if (!check && p.next != null && (state === 'updated' || state === 'created')) writeText(p.file, p.next)
      if (check && (state === 'updated' || state === 'created')) state = 'stale'
      views.push({ kind: p.kind, file: p.rel, state })
    }
  }
  const hot = syncHotRules(project, { check })
  return { external, views, hot }
}

export function viewsSummary(res) {
  const lines = []
  if (res.external) lines.push('views: generated_views is external in MANIFEST.md; strata leaves the views to the project generator')
  for (const v of res.views) lines.push(`${v.file}: ${v.state}`)
  for (const h of res.hot.results) lines.push(`${h.file} hot-rules block: ${h.state}`)
  if (res.hot.overflow) lines.push(`hot rules: ${res.hot.overflow} over the adapter block budget; curate the hot set`)
  return lines.join('\n')
}

export function drifted(res) {
  return res.views.filter((v) => v.state === 'stale').map((v) => v.file)
    .concat(res.hot.results.filter((h) => h.state === 'stale').map((h) => `${h.file} (hot-rules block)`))
}

export { relPosix, exists }
